language: node_js # 设置语言
node_js: stable # 设置相应的版本

# Travis-CI Caching
# cache:
#   directories:
#     - node_modules
#   yarn: true

# START: Build Lifecycle
install:
  # - npm install # 安装hexo及插件
  - true

before_script:
  # - npm install -g gulp
  - npm install -g hexo-cli

# script:
#   - gulp dist

script:
  - hexo init site
  - cd site
  - ls -la
  - yarn add hexo-renderer-ejs hexo-generator-archive hexo-generator-category-enhance hexo-generator-feed hexo-generator-index hexo-generator-tag
  - git clone https://github.com/SumiMakito/hexo-theme-Journal.git themes/journal
  - ls -la themes/journal
  - cd themes/journal
  - yarn install
  - ls -la ../..
  - cd ../..
  - sed -i 's|theme:\ landscape|theme:\ journal|g' _config.yml
  - sed -i "s|title:\OPSFORCE|title:\ Hexo|g" _config.yml
  - sed -i "s|author:\ John\ Doe|author:\ Jimmy\ Zhao|g" _config.yml
  - sed -i "s|language:|language:\ zh-tw|g" _config.yml
  - sed -i "s|timezone:|timezone:\ Asia/Shanghai|g" _config.yml
  - cat _config.yml
  - hexo clean # 清除
  - hexo generate # 生成静态网页

after_script:
  - cd public
  - echo 'demo.opsforce.org' > CNAME
  - git init
  - git config user.name "opsforce" # 修改name
  - git config user.email "i@opsforce.org" # 修改email
  - git add .
  - git commit -m "update site" # 此处看情况修改
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages # GH_TOKEN是在Travis中配置token的名称
# END: Build LifeCycle

branches:
  only:
    - master # 只监测master分支，对应的源码分支

env:
  global:
    - GH_REF: github.com/opsforce/site-incubator.git # 设置GH_REF，注意更改